<?php

echo json_encode(
    $data = array(
        [
            'id' => 1,
            'latitude' => 33.97645490538976,
            'longitude' => -118.36338138019211,
            'title' => "Bella Vida International Inc.",
            'location' => "1403 Centinela Ave Inglewood, Ca 90302",
            'city' => 1,
            'phone' => "(310)256-5140",
            'website' => "",
            'email' => "theservingspoon1@yahoo.com",
            'category' => "Restaurant / Catering",
            'marker_image' => "assets/img/items/v1.jpg",
            'gallery' => array(
                "assets/img/items/v1.jpg"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 2,
            'latitude' => 33.71815357078351,
            'longitude' => -118.28867661164767,
            'title' => "Maresp Corporation",
            'location' => "2840 S. Denison Ave, San Pedro CA 90731",
            'city' => 1,
            'phone' => "(213)908-8597",
            'website' => "",
            'email' => "",
            'category' => "Restaurant / Catering",
            'marker_image' => "assets/img/items/restaurant1.jpg",
            'gallery' => array(
                "assets/img/items/restaurant1.jpg"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 3,
            'latitude' => 34.15974076210964,
            'longitude' => -118.83717078026174,
            'title' => "Maete's Hair Design",
            'location' => "621 Hampshire Rd Apt. 301, Westlake Village CA 91361",
            'city' => 1,
            'phone' => "(805)368-7893",
            'website' => "",
            'email' => "sewingseeds100@gmail.com",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/saloon1.jpg",
            'gallery' => array(
                "assets/img/items/saloon1.jpg"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 4,
            'latitude' => 34.00144646993728,
            'longitude' => -118.35865333295243,
            'title' => "Florence Aliese Advancement Network",
            'location' => "4717 Don Lorenzo Drive, Apt. #5, Los Angeles, CA 90008",
            'city' => 1,
            'phone' => "(310)429-2059",
            'website' => "",
            'email' => "florencealiese@gmail.com",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/bus1.jpg",
            'gallery' => array(
                "assets/img/items/bus1.jpg"
            ),

            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Florence Aliese as a consulting firm has gone through a few iterations since 2013. It used to operate under Florence Aliese Development Company and in August 2020- reregistered it as Florence Aliese Advancement Network. ",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 5,
            'latitude' => 33.9436027936548,
            'longitude' => -118.23975945808783,
            'title' => "Watts Coffee House",
            'location' => "1827 E. 103rd St, Los Angeles CA 90002",
            'city' => 1,
            'phone' => "(323)804-9008",
            'website' => "http://places.singleplatform.com/watts-coffee-house/menu?ref=google",
            'email' => "wattscoffeehouse@sbcglobal.net ",
            'category' => "Restaurant / Catering",
            'opening_hours' => array(
                "Closed",
                "8am – 3pm",
                "8am – 3pm",
                "8am – 3pm",
                "8am – 3pm",
                "8am – 1pm",
                "10am – 3pm"
            ),
            'marker_image' => "assets/img/items/watt1.jpg",
            'gallery' => array(
                "assets/img/items/watt1.jpg",
                "assets/img/items/watt2.jpg"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Since opening in 1997, Watts Coffee House has served as a beloved meeting place for those in and around the neighborhood. Diners greet one another by name and with hearty pats on the back before settling in to eat heaping plates of stick-to-your-bones cooking. The dining room buzzes with a warm energy that speaks to its place in the history of Watts as a site of community building and activism. “When people have visitors, they’re proud to bring them in here and show us off,” Edwards said. “It’s a part of the pride of the community.”",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 6,
            'latitude' => 33.98941454827561,
            'longitude' => -118.34282230226567,
            'title' => "Chambers on Slauson ",
            'location' => "3923 W. Slauson Avenue, Los Angeles CA 90043",
            'city' => 1,
            'phone' => "(323)363-6682",
            'website' => "https://chambersonslauson.com/",
            'email' => "chambersshoes@sbcglobal.net",
            'category' => "Restaurant / Catering",
            'marker_image' => "assets/img/items/chambers1.jpg",
            'gallery' => array(
                "assets/img/items/chambers1.jpg",
                "assets/img/items/chambers2.jpg",
            ),

            'opening_hours' => array(
                "Closed",
                "9am - 5:30pm (last shine is at 5:15pm)",
                "9am - 5:30pm",
                "9am - 5:30pm ",
                "9am - 5:30pm ",
                "9am - 5:30pm ",
                "Closed"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Chambers Shoe Repair is a one stop full service shoe center specializing in shoe repairs and shoe shining. While shoes are our forte we can also handle just about any other leather personal item (ex. Wallets, Luggage, Holsters, Motorcycle Seats etc.) Stop in today for all your leather goods repairs and restoration needs. Mention this site and receive a free pair of heel plates on any pair of shoes.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 7,
            'latitude' => 33.96223452489747,
            'longitude' => -118.32770862289048,
            'title' => "Mingles Tea Bar",
            'location' => "8443 Crenshaw Blvd. Inglewood Blvd 90305",
            'city' => 1,
            'website' => "http://www.minglesteabar.com/",
            'phone' => "(323)875-8184",
            'email' => "minglesteabar@aol.com",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/mingle1.jpeg",
            'gallery' => array(
                "assets/img/items/mingle1.jpeg",
                "assets/img/items/mingle2.jpg",
            ),

            'opening_hours' => array(
                "10am – 6pm",
                "10am – 6pm",
                "10am – 6pm",
                "10am – 6pm",
                "10am – 6pm",
                "Closed",
                "Closed"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Mingles Tea Bar is a place to come relax, read, work and mingle. At Mingles Tea Bar we invite you to come in and enjoy jazz music, listen to spoken word or come to an art show. The owners' vision for Mingles Tea Bar is to be an establishment that will grow and be a part of the “New Inglewood”!",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 8,
            'latitude' => 34.01552769280724,
            'longitude' => -118.31366337886438,
            'title' => "Think Bigger Productions Inc ",
            'location' => "1808 Middleton Pl LA, CA 90062",
            'city' => 1,
            'website' => "",
            'phone' => "(323)819-1668",
            'email' => "dajuan@thinkbiggercoaching.com",
            'category' => "Entertainment",
            'marker_image' => "assets/img/items/entertainment.jpg",
            'gallery' => array(
                "assets/img/items/entertainment.jpg",
            ),
//            'opening_hours' => array(
//                "10am – 6pm",
//                "10am – 6pm",
//                "10am – 6pm",
//                "10am – 6pm",
//                "10am – 6pm",
//                "Closed",
//                "Closed"
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 9,
            'latitude' => 34.20031699228929,
            'longitude' => -118.45356671227766,
            'title' => "My Fish Stop LLC ",
            'location' => "7123 N Marisa Road, Van Nuys CA 91405",
            'city' => 1,
            'website' => "https://myfishstop.com/",
            'email' => "myfishstop@gmail.com",
            'phone' => "(818)454-4552",
            'category' => "Restaurant / Catering",
            'marker_image' => "assets/img/items/myfishstop1.jpg",
            'gallery' => array(
                "assets/img/items/myfishstop1.jpg",
                "assets/img/items/myfishstop11.jpg",
            ),

            'opening_hours' => array(
                "Closed",
                "Closed",
                "4 – 8pm",
                "4 – 8pm",
                "4 – 8pm",
                "1 – 7pm",
                "Closed"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 10,
            'latitude' => 34.11101918579724,
            'longitude' => -118.2505875802099,
            'title' => "Chicken N Chips Inc",
            'location' => "2728 FLETCHER DRIVE, LOS ANGELES CA 90039",
            'city' => 1,
            'website' => "https://chickennchips.com/",
            'email' => "cjones@chickennchips.com",
            'phone' => "(310)877-9857",
            'category' => "Restaurant / Catering",
            'marker_image' => "assets/img/items/cc1.jpg",
            'gallery' => array(
                "assets/img/items/cc2.png",
                "assets/img/items/cc1.jpg",
            ),

            'opening_hours' => array(
                "11am – 6:30pm",
                "11am – 6:30pm",
                "11am – 6:30pm",
                "11am – 6:30pm",
                "11am – 6:30pm",
                "11am – 6:30pm",
                "11am – 6:30pm"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Australian-inspired chicken shop serving plump, juicy, barn-raised chicken. Hand seasoned with our signature chicken salt recipe &amp; roasted to perfection.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 11,
            'latitude' => 33.97237850469381,
            'longitude' => -118.29135249843125,
            'title' => "Coffee Del Mundo, Inc",
            'location' => "7414 S Vermont Ave. Los Angeles, CA 90044",
            'city' => 1,
            'website' => "https://coffeedelmundo.com/",
            'email' => "jonathankinnard@gmail.com",
            'phone' => "(615)202-9047",
            'category' => "Restaurant / Catering",
            'marker_image' => "assets/img/items/coffem3.jpg",
            'gallery' => array(
                "assets/img/items/coffem1.jpg",
                "assets/img/items/coffem2.jpg",
                "assets/img/items/coffem3.jpg",
                "assets/img/items/coffem4.jpg",
            ),

            'opening_hours' => array(
                "Closed",
                "Closed",
                "7am – 1pm",
                "7am – 1pm",
                "7am – 1pm",
                "8am – 3pm",
                "8am – 8am"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Take your taste buds on a journey around the world as we deliver fresh roasted coffee direct from the source to you.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 12,
            'latitude' => 34.050858617620925,
            'longitude' => -118.35968620000138,
            'title' => "Nobody Jones Boutique",
            'location' => "1744 Carmona Ave. Los Angeles, CA 90019",
            'city' => 1,
            'website' => "http://nobodyjones.la/",
            'email' => "nobodyjonesinfo@aol.com",
            'phone' => "(323)493-9131",
            'category' => "Retail",
            'marker_image' => "assets/img/items/Nobody3.jpg",
            'gallery' => array(
                "assets/img/items/Nobody1.jpg",
                "assets/img/items/Nobody2.jpg",
            ),

            'opening_hours' => array(
                "Closed",
                "Closed",
                "Closed",
                "11am – 7pm",
                "11am – 7pm",
                "Closed",
                "Closed"
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "An L.A. Based Boutique that specializes in Jersey Dresses, Separates and Jumpsuits designed by Owner Odessa B. 5593 W. Pico Blvd. Los Angeles, CA",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 13,
            'latitude' => 34.05214834199628,
            'longitude' => -118.2657411157563,
            'title' => "Barista Life LA",
            'location' => "685 South Lucas Ave. Apt #409,  Los Angeles CA 90017 ",
            'city' => 1,
            'website' => "https://www.baristalifela.com/",
            'email' => "baristalifela@gmail.com",
            'phone' => "(323)445-2795",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/brista1.jpg",
            'gallery' => array(
                "assets/img/items/brista1.jpg",
                "assets/img/items/brista2.jpg",
                "assets/img/items/brista3.jpg",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "Closed",
//                "Closed",
//                "11am – 7pm",
//                "11am – 7pm",
//                "Closed",
//                "Closed"
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "I'm a Los Angeles native, born the daughter of two felons from South Central LA. 'Easy' is the last word I'd use to describe my upbringing but without the struggle I wouldn't be the proud Black Woman  I am today.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 14,
            'latitude' => 34.046824692629045,
            'longitude' => -118.46467550268798,
            'title' => "Ultimate Transformations Training LLC",
            'location' => "8732 Edmonton Place Inglewood CA 90305",
            'city' => 1,
            'website' => "http://www.ultimatetransformations.com/",
            'email' => "info@ultimatetransformations.com",
            'phone' => "(310)259-9755",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/ultimate1.jpg",
            'gallery' => array(
                "assets/img/items/ultimate1.jpg",
                "assets/img/items/ultimate2.jpg",
                "assets/img/items/ultimate3.png",
            ),

            'opening_hours' => array(
                "6am – 9pm",
                "6am – 9pm",
                "6am – 9pm",
                "6am – 9pm",
                "6am – 9pm",
                "7am – 3pm",
                "8am – 12pm",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "As a motivational speaker, Erich Nall’s charisma, wisdom and knowledge allow him to connect with diverse audiences on a broad range of topics. He draws upon his experience as a professional athlete, corporate businessman, community leader, personal trainer, husband and father of three girls, to motivate individuals and groups, young and old, to live their best lives. Erich Nall is the Owner and Founder of Ultimate Transformations Training (www.ultimatetransformations.com) in Los Angeles, California. He has coached and trained many successful professional athletes, actors, models and others in the entertainment industry for the past 18 years. The certified trainer, nutritionist, motivational speaker, and dedicated life coach is a regular guest and commentator on KJLH 102.3 FM's the \"Front Page with Dominique DiPrima\" and contributing writer for Volleyball Magazine and Our Weekly Newspaper in Los Angeles, CA.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 15,
            'latitude' => 34.07626270096425,
            'longitude' => -118.23826254963295,
            'title' => "Leacy’s Gifts - Leacy’s of Mt.Washington",
            'location' => "P.O. Box 41195, Los Angeles, Ca 90041",
            'city' => 1,
            'website' => "",
            'email' => "leacys@gmail.com",
            'phone' => "(213)500-0475",
            'category' => "Retail",
            'marker_image' => "assets/img/items/retail.jpeg",
            'gallery' => array(
                "assets/img/items/retail.jpeg",
            ),
//            'opening_hours' => array(
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "7am – 3pm",
//                "8am – 12pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "All other miscellaneous store retailers (including tobacco, candle, & trophy shops)",
            'marker_color' => "rgb(35, 124, 6)"
        ],

        [
            'id' => 16,
            'latitude' => 34.04052187730599,
            'longitude' => -118.37638089351425,
            'title' => "Leo Sullivan Multimedia, Inc.",
            'location' => "1976 S La Cienega Blvd, C296, Los Angeles, CA 90034",
            'city' => 1,
            'website' => "http://www.leosullivanmultimediainc.com/",
            'email' => "leo@afrokids.com",
            'phone' => "(323)491-8466",
            'category' => "Entertainment / Art Services",
            'marker_image' => "assets/img/items/leo.jpeg",
            'gallery' => array(
                "assets/img/items/Leo1.png",
                "assets/img/items/Leo2.png",
            ),
//            'opening_hours' => array(
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "7am – 3pm",
//                "8am – 12pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Building our children's self-esteem and cultural awareness with positive images through educational and recreational media teaching life lessons, family values, respect, and responsibility",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 17,
            'latitude' => 33.99487423182271,
            'longitude' => -118.32909470950366,
            'title' => "Heartsung",
            'location' => "5308 11th Avenue Los Angeles 90043",
            'city' => 1,
            'website' => "",
            'email' => "luraball@gmail.com",
            'phone' => "(213)400-3489",
            'category' => "Other",
            'marker_image' => "assets/img/items/business1.jpg",
            'gallery' => array(
                "assets/img/items/business1.jpg",
            ),
//            'opening_hours' => array(
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "7am – 3pm",
//                "8am – 12pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 18,
            'latitude' => 33.9756683129368,
            'longitude' => -118.3583302382944,
            'title' => "Diann Valentine Living Well, Inc.",
            'location' => "933 N. LaBrea Ave, Inglewood, CA 90302",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "(626)825-8445",
            'category' => "Retail",
            'marker_image' => "assets/img/items/black1.jpg",
            'gallery' => array(
                "assets/img/items/black1.jpg",
            ),
//            'opening_hours' => array(
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "7am – 3pm",
//                "8am – 12pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 19,
            'latitude' => 34.019718360054156,
            'longitude' => -118.25481477828814,
            'title' => "Heads Above, Inc",
            'location' => "2509 S CENTRAL AVE LOS ANGELES CA 90011-1634",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "(213)761-7236",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business1.jpg",
            'gallery' => array(
                "assets/img/items/business1.jpg",
            ),
//            'opening_hours' => array(
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "7am – 3pm",
//                "8am – 12pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 20,
            'latitude' => 34.10234217275739,
            'longitude' => -117.57385869820524,
            'title' => "Tashia S. Hilliard, DC LLC",
            'location' => "10601 Civic Center Drive Suite 100 G Rancho Cucamonga, CA 91730",
            'city' => 1,
            'website' => "https://www.drthilliard.com/",
            'email' => "",
            'phone' => "(909)313-2122",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/drthilliard1.png",
            'gallery' => array(
                "assets/img/items/drthilliard2.jpg",
                "assets/img/items/drthilliard3.jpg",
                "assets/img/items/drthilliard4.jpg",
            ),
//            'opening_hours' => array(
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "7am – 3pm",
//                "8am – 12pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Dr. Tashia S. Hilliard is a California State licensed chiropractor. She is a graduate of New York Chiropractic College and has 16 years experience in chiropractic and physiotherapy. She has practiced in her home states of New Jersey and New York and has now settled in Southern California. Dr. Hilliard has previously practiced in Upland, CA at Inland Naturopathic Medical Center and has branched into her own solo practice in Rancho Cucamonga, CA. She treats a plethora of musculoskeletal and physiological issues such as headaches to back pain, sports, work, and auto injuries. Dr. Hilliard also incorporates soft tissue massage, physiotherapy, rehabilitative exercises, and  herbal and nutritional recommendations with her product line Remedies by Dr. Hilliard to her patient's treatment plan. ",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 21,
            'latitude' => 34.157032037444985,
            'longitude' => -118.1492714523663,
            'title' => "Flo House",
            'location' => "637 N Raymond St, Pasadena CA 91103",
            'city' => 1,
            'website' => "",
            'email' => "phillyhaile@gmail.com",
            'phone' => "(323)802-8634",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "6am – 9pm",
//                "7am – 3pm",
//                "8am – 12pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],

        [
            'id' => 22,
            'latitude' => 34.00514459151408,
            'longitude' => -118.33166224635934,
            'title' => "Hot and Cool Cafe INC",
            'location' => "4331 Degnan Blvd. Los Angeles, CA 90008",
            'city' => 1,
            'website' => "http://hotandcoolcafe.com/",
            'email' => "tony@hotandcool.com",
            'phone' => "(408)706-8525",
            'category' => "Restaurant / Catering",
            'marker_image' => "assets/img/items/hc-logo.png",
            'gallery' => array(
                "assets/img/items/coffee-mug.png",
                "assets/img/items/coffe-hoodie.png",
                "assets/img/items/coffee.png",
            ),

            'opening_hours' => array(
                "10am – 8pm",
                "10am – 8pm",
                "10am – 8pm",
                "10am – 8pm",
                "10am – 8pm",
                "10am – 8pm",
                "12 – 8pm",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Hot + Cool Cafe tackles food inequity in South Central through our Senior Meal Program and partnering with LA Community Fridges.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 23,
            'latitude' => 33.99021918175185,
            'longitude' => -118.37572609376856,
            'title' => "Dominion Homes Inc",
            'location' => "5620 Bedford Avenue, Los Angeles, CA 90056",
            'city' => 1,
            'website' => "",
            'email' => "michaydel@gmail.com",
            'phone' => "(213)300-2874",
            'category' => "Other",
            'marker_image' => "assets/img/items/dom1.jpg",
            'gallery' => array(
                "assets/img/items/dom1.jpg",
            ),
//            'opening_hours' => array(
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "12 – 8pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 24,
            'latitude' => 34.0447487594114,
            'longitude' => -118.3485510799629,
            'title' => "Freshgenet",
            'location' => "1627 South Orange Dr Los Angeles CA 90019",
            'city' => 1,
            'website' => "",
            'email' => "freshgenet@freshgenet.com",
            'phone' => "(310)595-6681",
            'category' => "Retail",
            'marker_image' => "assets/img/items/retail.jpeg",
            'gallery' => array(
                "assets/img/items/retail.jpeg",
            ),
//            'opening_hours' => array(
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "12 – 8pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Small Black Woman own boutique located in Culver City, CA. We feature unique, stylish clothing designs for women. All of our clothing is designed or hand chosen by Freshgenet herself with style, quality and comfort the top priorities. Shop with us now!",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 25,
            'latitude' => 34.00211841597775,
            'longitude' => -118.39267806508849,
            'title' => "The Baker Group, LLC",
            'location' => "10736 Jefferson Blvd, #659, Culver City, CA  90230",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "(310)216-4722",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "12 – 8pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 26,
            'latitude' => 34.11531965954251,
            'longitude' => -118.17546926592829,
            'title' => "Lebanos",
            'location' => "6720 Crescent St. Los Angeles, CA 90042",
            'city' => 1,
            'website' => "",
            'email' => "leariebain@sbcglobal.net",
            'phone' => "(626)222-8428",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business1.jpg",
            'gallery' => array(
                "assets/img/items/business1.jpg",
            ),
//            'opening_hours' => array(
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "12 – 8pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 27,
            'latitude' => 34.12231104244691,
            'longitude' => -118.1880103368656,
            'title' => "Okan Entertainment",
            'location' => "568 Meridian Terrace, Los Angeles CA 90042",
            'city' => 1,
            'website' => "",
            'email' => "producerhashim@gmail.com",
            'phone' => "(310)8954246",
            'category' => "Entertainment",
            'marker_image' => "assets/img/items/entertainment.jpg",
            'gallery' => array(
                "assets/img/items/entertainment.jpg",
            ),
//            'opening_hours' => array(
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "12 – 8pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 28,
            'latitude' => 33.99465553094888,
            'longitude' => -118.37370397831096,
            'title' => "RJ PHYSICAL THERAPY GROUP, INC",
            'location' => "5218 S. SHERBOURNE DRIVE , LOS ANGELES, CA 90056",
            'city' => 1,
            'website' => "",
            'email' => "rjptgroup@yahoo.com",
            'phone' => "(310)7798901",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "12 – 8pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 29,
            'latitude' => 34.00825773666197,
            'longitude' => -118.2723015953865,
            'title' => "Apted ",
            'location' => "142 E 41st Place, Los Angeles CA ",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "(323)4590893",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "10am – 8pm",
//                "12 – 8pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 30,
            'latitude' => 34.0055294420112,
            'longitude' => -118.33173213759181,
            'title' => "Ride On! Bike Shop LLC ",
            'location' => "4319. Degnan Blvd. Los Angeles CA ",
            'city' => 1,
            'website' => "https://www.rideonbikeshop.com/",
            'email' => "info@rideonbikeshop.com",
            'phone' => "(323)8635434",
            'category' => "Professional Service / Retail",
            'marker_image' => "assets/img/items/ridelogo.jpg",
            'gallery' => array(
                "assets/img/items/ridelogo.jpg",
                "assets/img/items/ride1.jpg",
                "assets/img/items/ride2.jpg",
            ),

            'opening_hours' => array(
                "Closed",
                "12 – 4pm",
                "12 – 4pm",
                "12 – 4pm",
                "12 – 4pm",
                "12 – 4pm",
                "12 – 4pm",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "There has always been a bicycle culture in South Los Angeles.  Groups such as Major Motion Cycling Club, who take long rides on road bikes, and Real Rydaz, who customize their bicycles in a similar fashion as lowrider cars, have been in existence for decades.  Many people ride bikes around their neighborhoods, or have an old bike sitting in their garage.  But one issue for years has been that there are very few places to purchase or repair bicycles in the area.",
            'marker_color' => "rgb(35, 124, 6)"
        ],

        [
            'id' => 31,
            'latitude' => 34.06648912784546,
            'longitude' => -118.3530773071872,
            'title' => "Prothro Eats INC ",
            'location' => "430 S. Fuller Ave. Suite 9K Los Angeles, Ca 90036",
            'city' => 1,
            'website' => "",
            'email' => "tasha.prothro@gmail.com",
            'phone' => "(323)8391420",
            'category' => "Restaurant / Catering",
            'marker_image' => "assets/img/items/restaurant1.jpg",
            'gallery' => array(
                "assets/img/items/restaurant1.jpg",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 32,
            'latitude' => 34.04002635956266,
            'longitude' => -118.32294387862919,
            'title' => "BLKNWS LLC",
            'location' => "3508 W. Washington Blvd. Los Angeles CA 90007",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "(917)4394592",
            'category' => "Entertainment / Media",
            'marker_image' => "assets/img/items/step2.png",
            'gallery' => array(
                "assets/img/items/step2.png",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 33,
            'latitude' => 34.06312983905065,
            'longitude' => -118.36477576729678,
            'title' => "Come Up Markets LLC",
            'location' => "6230 Wilshire Blvd., #1223 Los Angeles, CA 90048",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "(510)7080724",
            'category' => "Professional Service / Retail",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 34,
            'latitude' => 33.963504535887985,
            'longitude' => -118.29210044064848,
            'title' => "Step1 TV Studios",
            'location' => "8301 S. Vermont Ave Unit F Los Angeles Ca. 90044 ",
            'city' => 1,
            'website' => "http://www.step1tv.com/",
            'email' => "",
            'phone' => "(510)7080724",
            'category' => "Entertainment / Media",
            'marker_image' => "assets/img/items/step1.jpg",
            'gallery' => array(
                "assets/img/items/step1.jpg",
                "assets/img/items/step2.png",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "It was a simple plan. To create a  global platform for future stars to shine on TV. It started with our mobile app (STEP1TV) and grew into a linear channel, the first television station is based in Los Angeles CA on Ova TV 31.9 and currently broadcasts popular content including Eric B's Ghetto Court, A Taste of Hunney, Changing Steps & The IndiePendents.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 35,
            'latitude' => 34.00383812794534,
            'longitude' => -118.28591787924947,
            'title' => "Quentissential Gardens",
            'location' => "662 West Vernon Avenue, Los Angeles CA 90037",
            'city' => 1,
            'website' => "https://quintessentialgardens.net/",
            'email' => "quentissentialgardens@gmail.com",
            'phone' => "(415) 652-5394",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "We are a fine gardening business with an emphasis on organic, natural, sustainable horticulture practices. These practices use time tested methods that have as little impact on the environment as possible. We try to utilize local sources for supplies as often as possible and support our local businesses. We use minimal equipment to reduce the noise pollution and energy consumption that modern landscaping has become notorious for.",
            'marker_color' => "rgb(35, 124, 6)"
        ],

        [
            'id' => 36,
            'latitude' => 34.062341439217555,
            'longitude' => -118.3479234493863,
            'title' => "Natural Hair and the Law",
            'location' => "5482 Wilshire Blvd #184, Los Angeles CA 90036",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "(323) 209-5575",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 37,
            'latitude' => 33.94727396489912,
            'longitude' => -118.38304641132068,
            'title' => "Loup Workspace LLC",
            'location' => "5777 West Century Blvd #1110, Los Angeles CA 90045",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "(424) 800-2135",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 38,
            'latitude' => 33.88398695650475,
            'longitude' => -118.0364802835748,
            'title' => "Faith Com Inc. dba FCI Management",
            'location' => "13850 Cerritos Corporate Dr. Unit D, Cerritos CA 90703",
            'city' => 1,
            'website' => "",
            'email' => "patwatts@fcimgt.com",
            'phone' => "(310) 418-3211",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "Closed",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//                "12 – 4pm",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 39,
            'latitude' => 33.95880753040761,
            'longitude' => -118.3213726242062,
            'title' => "I.C. Isabella Designs, INC",
            'location' => "8711 South 4th Avenue, Inglewood CA 90305 ",
            'city' => 1,
            'website' => "https://www.icisabelladesigns.com/",
            'email' => "icisabelladesigns@gmail.com",
            'phone' => "(323) 206-8207",
            'category' => "Retail",
            'marker_image' => "assets/img/items/icisabelladesigns3.jpg",
            'gallery' => array(
                "assets/img/items/icisabelladesigns1.jpg",
                "assets/img/items/icisabelladesigns2.jpg",
            ),

            'opening_hours' => array(
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "Closed",
                "Closed",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "The creation of I.C. Isabella Designs, INC began In 2014, Courtney Johnson’s wife, a former ballet teacher, started having trouble finding unique and stylish apparel that accentuates her curvy body. Courtney began designing specialty outfits for his wife, and the company soon grew to an upscale “Ready to Wear” Curvy Apparel Company that brings new designs and stylish fits for women with curvy bodies who are not sized 0-4.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 40,
            'latitude' => 33.9587007403082,
            'longitude' => -118.3212224224271,
            'title' => "Henderickson & Wright FCC",
            'location' => "7867 Crenshaw Blvd Los Angeles CA 90043",
            'city' => 1,
            'website' => "",
            'email' => "jhenderson@transcalservices.com",
            'phone' => "(323) 750-7441",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],

        [
            'id' => 41,
            'latitude' => 33.97692920832738,
            'longitude' => -118.36590562487964,
            'title' => "EL Mosby Enterprises LLC.",
            'location' => "1541 Centinela Avenue, Inglewood CA 90302",
            'city' => 1,
            'website' => "",
            'email' => "elgin1911@aol.com",
            'phone' => "",
            'category' => "Personal Care",
            'marker_image' => "assets/img/items/enterprise.jpg",
            'gallery' => array(
                "assets/img/items/enterprise.jpg",
            ),
//
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 42,
            'latitude' => 34.15435930113851,
            'longitude' => -118.64792175190506,
            'title' => "Efface Aesthetics",
            'location' => "23901 Calabasas Rd #1010, Calabasas CA 91302",
            'city' => 1,
            'website' => "",
            'email' => "effaceroberta@gmail.com",
            'phone' => "",
            'category' => "Personal Care",
            'marker_image' => "assets/img/items/cropped-header-logo.png",
            'gallery' => array(
                "assets/img/items/personal-care.jpg",
            ),
//
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 43,
            'latitude' => 33.787730680572615,
            'longitude' => -118.32450609578063,
            'title' => "Total Serenity",
            'location' => "25917 Viana Avenue, Lomita CA 90717",
            'city' => 1,
            'website' => "",
            'email' => "rozzig642@hotmail.com",
            'phone' => "",
            'category' => "Personal Care",
            'marker_image' => "assets/img/items/personal-care.jpg",
            'gallery' => array(
                "assets/img/items/personal-care.jpg",
            ),
//
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 44,
            'latitude' => 33.94188577857338,
            'longitude' => -118.30941091027621,
            'title' => "Taking All Fades Barber Shop",
            'location' => "10401 S. Western Avenue, LA CA 90047",
            'city' => 1,
            'website' => "",
            'email' => "",
            'phone' => "",
            'category' => "Personal Care",
            'marker_image' => "assets/img/items/barber.jpeg",
            'gallery' => array(
                "assets/img/items/barber.jpeg",
            ),
//
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 45,
            'latitude' => 33.98754344834608,
            'longitude' => -118.30927998038257,
            'title' => "MISLA- Made In South LA.",
            'location' => "5923 S. Western Avenue, LA CA 90047",
            'city' => 1,
            'website' => "https://misla.org/",
            'email' => "info@misla.org",
            'phone' => "424-253-8873",
            'category' => "Technology",
            'marker_image' => "assets/img/items/misla.png",
            'gallery' => array(
                "assets/img/items/misla.png",
                "assets/img/items/District2.jpg",
            ),
//, , www.MISLA.org
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "We are a band of rogue creatives and developers headquartered in South Central Los Angeles. We train historically underserved youth in the local communities and distressed communities around the world in web design, multimedia, and digital marketing.",
            'marker_color' => "rgb(35, 124, 6)"
        ],

        [
            'id' => 46,
            'latitude' => 34.04510496010527,
            'longitude' => -118.3340164955167,
            'title' => "Intuitive Real Estate Services",
            'location' => "1649 Buckingham Road, LA CA 90019-5904",
            'city' => 1,
            'website' => "",
            'email' => "jwilliams@in2-res.com",
            'phone' => "",
            'category' => "Construction/Maintenance/Property Management",
            'marker_image' => "assets/img/items/real.jpeg",
            'gallery' => array(
                "assets/img/items/real.jpeg",
            ),
//
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 47,
            'latitude' => 33.978756488147354,
            'longitude' => -118.37207265035224,
            'title' => "Mike Conway Termite Control Inc.",
            'location' => "6709 La Tijera Blvd #235 LA, CA 90045",
            'city' => 1,
            'website' => "",
            'email' => "mike@mikeconwaytermitecontrol.com",
            'phone' => "310-677-1459",
            'category' => "Construction/Maintenance/Property Management",
            'marker_image' => "assets/img/items/mike1.jpg",
            'gallery' => array(
                "assets/img/items/mike1.jpg",
                "assets/img/items/mike2.jpg",
            ),

            'opening_hours' => array(
                "8am – 5pm",
                "8am – 5pm",
                "8am – 5pm",
                "8am – 5pm",
                "8am – 5pm",
                "8am – 5pm",
                "Closed",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "We Specialize in termite control, fumigations, localized treatments, fungus treatments & structural repair.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 48,
            'latitude' => 33.996064472528495,
            'longitude' => -118.27821784252092,
            'title' => "New Life Economic Development, Inc.",
            'location' => "5200 S Broadway Office, Los Angeles, CA 90037",
            'city' => 1,
            'website' => "http://newlifeedc.org/",
            'email' => "jheath@newlifeedc.org",
            'phone' => "+13237785433",
            'category' => "Construction/Maintenance/Property Management",
            'marker_image' => "assets/img/items/newlife1.png",
            'gallery' => array(
                "assets/img/items/newlife2.jpg",
                "assets/img/items/newlife3.jpg",
            ),

            'opening_hours' => array(
                "10am – 5pm",
                "10am – 5pm",
                "10am – 5pm",
                "10am – 5pm",
                "10am – 5pm",
                "Closed",
                "Closed",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "New Life Economic Development is a community-based 501(c)(3) nonprofit organization that specializes in providing development, compliance, and socially responsive management services for multifamily affordable rental properties in Southern California As a nonprofit, we are mission driven and bring extra value to property owners, residents, and the community. We save property owners time and money by proactively finding and repairing compliance issues and optimizing operations. We benefit residents by providing programs and amenities that enhance quality of life. And we support the local community by hiring employees who live in the areas we serve. We are proud to have a track record of extending rental opportunities to veterans and the recently homeless.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 49,
            'latitude' => 34.05237792474182,
            'longitude' => -118.25281883515338,
            'title' => "SCA Strategic Partnerships International, LLC",
            'location' => "355 S. Grand Avenue #2450, LA CA 90071",
            'city' => 1,
            'website' => "",
            'email' => "joyce@scastrategic.com",
            'phone' => "310-677-1459",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//
//            'opening_hours' => array(
//                "8am – 5pm",
//                "8am – 5pm",
//                "8am – 5pm",
//                "8am – 5pm",
//                "8am – 5pm",
//                "8am – 5pm",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 50,
            'latitude' => 33.99272307931058,
            'longitude' => -118.33476604044066,
            'title' => "DBA- K Style Media",
            'location' => "5415 Chesley Ave, Los Angeles CA 90043",
            'city' => 1,
            'website' => "",
            'email' => "feliciakstyle@gmail.com",
            'phone' => "(424) 777-5828",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//
//            'opening_hours' => array(
//                "8am – 5pm",
//                "8am – 5pm",
//                "8am – 5pm",
//                "8am – 5pm",
//                "8am – 5pm",
//                "8am – 5pm",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],

        [
            'id' => 51,
            'latitude' => 33.855770794457555,
            'longitude' => -118.23637559462185,
            'title' => "We Pull Up - Mobile Car Wash & Detail",
            'location' => "19307 Craigjon Aveue, Carson CA 90746",
            'city' => 1,
            'website' => "https://pullupmobilecarwash.com/",
            'email' => "wepullup@icloud.com",
            'phone' => "(213)308-1450",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/pullupmobilecarwash1.jpg",
            'gallery' => array(
                "assets/img/items/pullupmobilecarwash2.jpg",
                "assets/img/items/pullupmobilecarwash3.jpg",
            ),

            'opening_hours' => array(
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "Closed",
                "Closed",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "We're more than your average car wash! We can tailor fit your needs at the click of a button, at your convenience, at your requested location! We will pull up to you where ever you are ready to clean your car. We provide detailed hand washing, both interior and exterior, for those who want a little extra attention to detail.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 52,
            'latitude' => 33.98438036816164,
            'longitude' => -118.30925999438251,
            'title' => "TransCal Services, LLC",
            'location' => "6109 S. Western Avenue Ste. 308, LA CA 90047",
            'city' => 1,
            'website' => "",
            'email' => "jhenderson@transcalservices.com",
            'phone' => "",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/business2.jpeg",
            'gallery' => array(
                "assets/img/items/business2.jpeg",
            ),
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 53,
            'latitude' => 33.86676212477818,
            'longitude' => -118.08330351193875,
            'title' => "Freeway Easy / Original Homestudy",
            'location' => "18173 Pioneer Blvd 2nd fl ste. S-T, Artesia, CA 90701",
            'city' => 1,
            'website' => "https://freewayeasy.com/",
            'email' => "driving@freewayeasy.com",
            'phone' => "323-600-7574",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/free1.png",
            'gallery' => array(
                "assets/img/items/free1.png",
            ),
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "We offer On-Line Driver’s Education and Behind- the- wheel training for students who are at least 15 ½ years old or older. Click Here for Driver’s Ed.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 54,
            'latitude' => 33.99733456460543,
            'longitude' => -118.29452539574928,
            'title' => "Bryte Savings, LLC.",
            'location' => "1121 West 51st Street, LA CA 90037",
            'city' => 1,
            'website' => "http://www.brytesavings.com/",
            'email' => "brytesavings@gmail.com",
            'phone' => "323-532-9826",
            'category' => "Professional Service",
            'marker_image' => "assets/img/items/logo-c.png",
            'gallery' => array(
                "assets/img/items/logo-c.png",
            ),
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "Bryte Savings, LLC is an LED lighting manufacturing/distributor that specializes in Big Lumen™ plug-n-play technology. Bryte Savings, LLC provides state of the art, high quality LED lamps and fixtures specifically for replacing HID high-bay lighting.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 55,
            'latitude' => 33.97964798298957,
            'longitude' => -118.38217627902914,
            'title' => "TCG Footwear",
            'location' => "6534 Shenandoah Avenue, LA CA 90056",
            'city' => 1,
            'website' => "",
            'email' => "kyle@tcgfootwear.com",
            'phone' => "(310) 910-2498",
            'category' => "Retail",
            'marker_image' => "assets/img/items/retail.jpeg",
            'gallery' => array(
                "assets/img/items/retail.jpeg",
            ),
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],

        [
            'id' => 56,
            'latitude' => 34.24542630028135,
            'longitude' => -118.46686146706308,
            'title' => "Witt Events",
            'location' => "9620 Sepulveda Blvd Unit 55, North Hills CA 91343",
            'city' => 1,
            'website' => "",
            'email' => "colinewitt@gmail.com",
            'phone' => "(818) 675 -5895",
            'category' => "Entertainment",
            'marker_image' => "assets/img/items/entertainment.jpg",
            'gallery' => array(
                "assets/img/items/entertainment.jpg",
            ),
//            'opening_hours' => array(
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "9am – 5pm",
//                "Closed",
//                "Closed",
//            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 57,
            'latitude' => 33.82076966978227,
            'longitude' => -118.18981006821765,
            'title' => "Rainbow Promotions LLC",
            'location' => "3505 Long Beach Blvd 2G, Long Beach CA",
            'city' => 1,
            'website' => "http://www.rainbowpromotions.com/",
            'email' => "kimbenoit@aol.com",
            'phone' => "(562) 424.0013",
            'category' => "Entertainment ",
            'marker_image' => "assets/img/items/Rainbow1.png",
            'gallery' => array(
                "assets/img/items/Rainbow2.png",
                "assets/img/items/Rainbow3.jpg",
                "assets/img/items/Rainbow4.jpg",
            ),

            'opening_hours' => array(
                "10am – 5pm",
                "10am – 5pm",
                "10am – 5pm",
                "10am – 5pm",
                "10am – 5pm",
                "Closed",
                "Closed",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "We are Rainbow Promotions, a premier event management corporation With over 30 years of professional experience in a variety of venues, we specialize in creating and managing innovative projects including festivals, concerts, thematic galas, corporate parties and special events. Our events showcase some of the greatest artists of our time, multiple Grammy award winners and nominees, as well as up-and-coming new talent.",
            'marker_color' => "rgb(35, 124, 6)"
        ],
        [
            'id' => 58,
            'latitude' => 33.95666944830631,
            'longitude' => -118.30496865423218,
            'title' => "Martgol's Magic Inc",
            'location' => "345 N Maple Dr # P2, Beverly Hills, CA 90210",
            'city' => 1,
            'website' => "http://martgolsmagic.com/",
            'email' => "martgol@earthlink.net",
            'phone' => "(424) 777-5828",
            'category' => "Professional Service",
           'marker_image' => "assets/img/items/martgolsmagic.png",
            'gallery' => array(
                "assets/img/items/martgolsmagic.png",
            ),

            'opening_hours' => array(
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "9am – 5pm",
                "Closed",
                "Closed",
            ),
            'rating' => "",
            'reviews_number' => "",
            'url' => "",
            'description' => "",
            'marker_color' => "rgb(35, 124, 6)"
        ],

    )
);

